/* -----------------------------------------------------------------------------
 * This file was automatically generated by a Python script.
 * PLEASE DON'T EDIT IT DIRECTLY, your changes would be overwritten the next time the script is run.
 * Instead, go to "generate_variables.py" and edit the "all_variable_includes" function there.
 * -----------------------------------------------------------------------------
 */

#include <Cool/Camera/Camera.h>
#include <Cool/Variables/Variables.h>
