#pragma once

#include <Cool/Dependencies/Input.h>
#include <Cool/Dependencies/InputDefinition.h>
#include "FunctionSignature.h"
#include "NodeInputDefinition.h"

namespace Lab {

struct FunctionPieces {
    std::string       name;
    FunctionSignature signature;
    std::string       body;
};

struct NodeDefinition_Data {
    std::string                 name;
    FunctionSignature           signature;
    std::string                 function_body;
    std::vector<FunctionPieces> helper_functions{};

    std::vector<NodeInputDefinition>      inputs{};         // Things that can only come from a pin
    std::vector<Cool::AnyInputDefinition> properties{};     // Things that will default to a widget on the node if nothing is plugged into the pin
    std::vector<std::string>              output_indices{}; // Names of the indices generated by an iteration / duplication process
};

class NodeDefinition {
public:
    NodeDefinition(NodeDefinition_Data const&);

    auto name() const -> auto const& { return _data.name; }
    auto signature() const -> auto const& { return _data.signature; }
    auto function_body() const -> auto const& { return _data.function_body; }
    auto inputs() const -> auto const& { return _data.inputs; }
    auto properties() const -> auto const& { return _data.properties; }
    auto output_indices() const -> auto const& { return _data.output_indices; }
    auto helper_functions() const -> auto const& { return _data.helper_functions; }

private:
    NodeDefinition_Data _data;
};

} // namespace Lab
